// ============================================================
// Yardly plantedatabase — norske hagevekster
// ~180 planter fordelt på 9 kategorier
// ============================================================

export const CAT_ORDER = ['grønnsak','bær','frukt','urt','rose','staude','busk','tre','prydplante']

export const CAT_LABELS = {
  grønnsak:   'Grønnsaker',
  bær:        'Bær',
  frukt:      'Frukt',
  urt:        'Urter',
  rose:       'Roser',
  staude:     'Stauder (flerårige)',
  busk:       'Busker og klatreplanter',
  tre:        'Trær',
  prydplante: 'Prydplanter og løkblomster',
}

export const PLANT_DB = [
  // ─────────────── GRØNNSAKER ───────────────
  { key:'tomat',        name:'Tomat',        emoji:'🍅', cat:'grønnsak', harvest:true,  pricePerKg:30,
    seasonal:{5:['Plant ut etter 15. mai'],6:['Gjødsle','Fjern sideskudd'],7:['Vann jevnt'],8:['Høst modne tomater'],9:['Høst alle'],10:['Rydde opp']} },
  { key:'agurk',        name:'Agurk',        emoji:'🥒', cat:'grønnsak', harvest:true,  pricePerKg:20,
    seasonal:{5:['Plant ut etter 20. mai'],6:['Gjødsle, klyp toppen'],7:['Høst hyppig'],8:['Høst daglig'],9:['Avslutt sesongen']} },
  { key:'gulrot',       name:'Gulrot',       emoji:'🥕', cat:'grønnsak', harvest:true,  pricePerKg:15,
    seasonal:{4:['Så utendørs fra midten av april'],5:['Tynn ut til 5 cm'],6:['Luke ugras'],7:['Babygulrøtter kan høstes'],8:['Høst fortløpende'],9:['Høst resten'],10:['Dekk med halm']} },
  { key:'potet',        name:'Potet',        emoji:'🥔', cat:'grønnsak', harvest:true,  pricePerKg:12,
    seasonal:{3:['Grønnspiring innendørs'],5:['Plant etter siste frost'],6:['Hypp opp jord'],7:['Hypp igjen'],8:['Høst nye poteter'],9:['Høst alle']} },
  { key:'gresskar',     name:'Gresskar',     emoji:'🎃', cat:'grønnsak', harvest:true,  pricePerKg:10,
    seasonal:{4:['Så innendørs'],5:['Plant ut'],6:['Klyp sideranker'],8:['Begynn høsting'],9:['Høst alle før frost']} },
  { key:'løk',          name:'Løk',          emoji:'🧅', cat:'grønnsak', harvest:true,  pricePerKg:10,
    seasonal:{4:['Plant løkplanter'],5:['Gjødsle'],6:['Vann jevnt'],7:['Slutt å gjødsle'],8:['Høst når topper faller'],9:['Tørk og lagre']} },
  { key:'hvitløk',      name:'Hvitløk',      emoji:'🧄', cat:'grønnsak', harvest:true,  pricePerKg:80,
    seasonal:{9:['Plant fedd på høsten'],4:['Gjødsle om våren'],5:['Fjern blomsterstilker'],7:['Høst når bladene gulner']} },
  { key:'purre',        name:'Purre',        emoji:'🌿', cat:'grønnsak', harvest:true,  pricePerKg:20,
    seasonal:{2:['Så innendørs'],5:['Plant ut'],6:['Hypp opp jord rundt'],8:['Kan høste'],9:['Høst'],10:['Høst resten']} },
  { key:'brokkoli',     name:'Brokkoli',     emoji:'🥦', cat:'grønnsak', harvest:true,  pricePerKg:25,
    seasonal:{3:['Så innendørs'],5:['Plant ut'],6:['Gjødsle med nitrogen'],7:['Høst hode før blomstring'],8:['Høst sideskudd']} },
  { key:'blomkål',      name:'Blomkål',      emoji:'🥦', cat:'grønnsak', harvest:true,  pricePerKg:22,
    seasonal:{3:['Så innendørs'],5:['Plant ut'],7:['Bind blader over hodet'],8:['Høst når fast og hvitt']} },
  { key:'hodekål',      name:'Hodekål',      emoji:'🥬', cat:'grønnsak', harvest:true,  pricePerKg:10,
    seasonal:{3:['Så innendørs'],5:['Plant ut'],6:['Gjødsle'],8:['Høst'],9:['Høst']} },
  { key:'rosenkål',     name:'Rosenkål',     emoji:'🥬', cat:'grønnsak', harvest:true,  pricePerKg:28,
    seasonal:{3:['Så innendørs'],5:['Plant ut'],9:['Høst nedenfra'],10:['Høst etter frost — bedre smak'],11:['Høst resten']} },
  { key:'spinat',       name:'Spinat',       emoji:'🥬', cat:'grønnsak', harvest:true,  pricePerKg:40,
    seasonal:{4:['Så direkte'],5:['Tynn ut'],6:['Høst ytterblader'],7:['Høst alt — trekker opp i varme']} },
  { key:'salat',        name:'Salat',        emoji:'🥗', cat:'grønnsak', harvest:true,  pricePerKg:30,
    seasonal:{4:['Så innendørs/ute'],5:['Plant ut'],6:['Høst ytterblader'],7:['Høst hele hoder'],8:['Ny sårunde']} },
  { key:'paprika',      name:'Paprika',      emoji:'🫑', cat:'grønnsak', harvest:true,  pricePerKg:50,
    seasonal:{3:['Så innendørs'],5:['Plant i drivhus'],7:['Høst grønn'],8:['Høst rød/gul']} },
  { key:'squash',       name:'Squash',       emoji:'🟢', cat:'grønnsak', harvest:true,  pricePerKg:15,
    seasonal:{5:['Plant ut etter frost'],6:['Høst unge frukter'],7:['Høst daglig'],8:['Høst'],9:['Avslutt']} },
  { key:'bønner',       name:'Bønner',       emoji:'🫘', cat:'grønnsak', harvest:true,  pricePerKg:30,
    seasonal:{5:['Så direkte etter siste frost'],6:['Sett opp støtte'],7:['Høst hyppig'],8:['Høst fortløpende']} },
  { key:'erter',        name:'Erter',        emoji:'🟢', cat:'grønnsak', harvest:true,  pricePerKg:25,
    seasonal:{4:['Så direkte'],5:['Sett opp nett'],6:['Høst daglig'],7:['Høst'],8:['Rydde opp']} },
  { key:'rødbete',      name:'Rødbete',      emoji:'🟣', cat:'grønnsak', harvest:true,  pricePerKg:18,
    seasonal:{4:['Så direkte'],5:['Tynn ut til 8 cm'],7:['Babybeter kan høstes'],8:['Høst'],9:['Høst resten']} },
  { key:'pastinakk',    name:'Pastinakk',    emoji:'🥕', cat:'grønnsak', harvest:true,  pricePerKg:18,
    seasonal:{4:['Så tidlig'],6:['Tynn ut'],9:['Høst etter frost — søtere'],10:['Høst resten']} },
  { key:'kålrabi',      name:'Kålrabi',      emoji:'🟢', cat:'grønnsak', harvest:true,  pricePerKg:15,
    seasonal:{4:['Så innendørs'],5:['Plant ut'],6:['Høst unge, ca. 6 cm'],7:['Høst']} },
  { key:'reddik',       name:'Reddik',       emoji:'🔴', cat:'grønnsak', harvest:true,  pricePerKg:20,
    seasonal:{4:['Så direkte'],5:['Høst etter 4 uker'],6:['Ny sårunde'],8:['Ny sårunde for høsten']} },
  { key:'mais',         name:'Mais',         emoji:'🌽', cat:'grønnsak', harvest:true,  pricePerKg:15,
    seasonal:{5:['Plant ut etter 20. mai'],6:['Gjødsle'],8:['Høst når silkehårene er brune'],9:['Høst resten']} },
  { key:'mangold',      name:'Mangold',      emoji:'🥬', cat:'grønnsak', harvest:true,  pricePerKg:35,
    seasonal:{4:['Så innendørs'],5:['Plant ut'],6:['Høst ytterblader'],7:['Høst'],8:['Høst'],9:['Høst']} },
  { key:'asparges',     name:'Asparges',     emoji:'🌱', cat:'grønnsak', harvest:true,  pricePerKg:80,
    seasonal:{3:['Gjødsle godt tidlig vår'],4:['Høst skudd (fra år 3)'],5:['La vokse til bregne etter høsting'],10:['Klipp ned visne stengler']} },
  { key:'rabarbra',     name:'Rabarbra',     emoji:'🌿', cat:'grønnsak', harvest:true,  pricePerKg:20,
    seasonal:{3:['Gjødsle tidlig vår'],4:['Første skudd'],5:['Høst stilker, la noen stå'],6:['Høst siste runde'],7:['La planten hvile']} },
  { key:'fennikel',     name:'Fennikel',     emoji:'🌿', cat:'grønnsak', harvest:true,  pricePerKg:30,
    seasonal:{5:['Plant ut'],6:['Hypp opp jord rundt bulben'],8:['Høst når bulb er 8-10 cm']} },
  { key:'stangselleri', name:'Stangselleri', emoji:'🌿', cat:'grønnsak', harvest:true,  pricePerKg:25,
    seasonal:{3:['Så innendørs'],5:['Plant ut'],7:['Kan høste ytterstengler'],8:['Høst'],9:['Høst resten']} },
  { key:'kinakål',      name:'Kinakål',      emoji:'🥬', cat:'grønnsak', harvest:true,  pricePerKg:15,
    seasonal:{7:['Så direkte — bolter lett i varme'],8:['Høst'],9:['Høst']} },
  // ─────────────── BÆR ───────────────
  { key:'jordbær',      name:'Jordbær',      emoji:'🍓', cat:'bær', harvest:true,  pricePerKg:60,
    seasonal:{3:['Fjern gammelt løv'],4:['Gjødsle med bærgjødsel','Plant nye planter'],5:['Legg ut jordbærhalm'],6:['Høst daglig','Fjern utløpere'],7:['Høst siste bær'],8:['Klipp ned løv','Gjødsle for neste år']} },
  { key:'bringebær',    name:'Bringebær',    emoji:'🍒', cat:'bær', harvest:true,  pricePerKg:80,
    seasonal:{3:['Beskjær brukte skudd til bakken'],4:['Gjødsle med bærgjødsel'],7:['Høst daglig — modner raskt'],8:['Klipp ned brukte skudd, la nye stå']} },
  { key:'solbær',       name:'Solbær',       emoji:'🫐', cat:'bær', harvest:true,  pricePerKg:50,
    seasonal:{3:['Beskjær eldre grener'],4:['Gjødsle'],7:['Høst hele klaser'],8:['Gjødsle etter høsting']} },
  { key:'rips-rød',     name:'Rips (rød)',   emoji:'🍇', cat:'bær', harvest:true,  pricePerKg:45,
    seasonal:{3:['Beskjær'],4:['Gjødsle'],7:['Høst klaser'],8:['Gjødsle etter høsting']} },
  { key:'rips-hvit',    name:'Rips (hvit)',  emoji:'🍇', cat:'bær', harvest:true,  pricePerKg:50,
    seasonal:{3:['Beskjær'],4:['Gjødsle'],7:['Høst klaser — mildere enn rød'],8:['Gjødsle']} },
  { key:'stikkelsbær',  name:'Stikkelsbær',  emoji:'🟡', cat:'bær', harvest:true,  pricePerKg:40,
    seasonal:{3:['Beskjær buske — åpent sentrum'],4:['Gjødsle'],7:['Høst umodne for syltetøy'],8:['Høst modne']} },
  { key:'bjørnebær',    name:'Bjørnebær',    emoji:'⚫', cat:'bær', harvest:true,  pricePerKg:90,
    seasonal:{4:['Fest skudd til gitter'],7:['Høst daglig'],8:['Høst'],9:['Klipp ned brukte skudd']} },
  { key:'aronia',       name:'Aronia',       emoji:'🟤', cat:'bær', harvest:true,  pricePerKg:30,
    seasonal:{4:['Lett beskjæring'],8:['Høst klaser'],9:['Høst resten — sødme øker etter frost']} },
  { key:'blåbær',       name:'Blåbær (hage)',emoji:'🫐', cat:'bær', harvest:true,  pricePerKg:70,
    seasonal:{4:['Gjødsle med sur gjødsel (pH 4-5)'],6:['Nett over buskene'],7:['Høst daglig'],8:['Høst']} },
  { key:'hyllebær',     name:'Hyllebær',     emoji:'🌿', cat:'bær', harvest:true,  pricePerKg:20,
    seasonal:{4:['Beskjær om nødvendig'],6:['Hvit blomstring'],9:['Høst blå/svarte klaser'],10:['Kok saft eller syltetøy']} },
  { key:'tyttebær',     name:'Tyttebær (hage)',emoji:'🔴', cat:'bær', harvest:true, pricePerKg:60,
    seasonal:{4:['Gjødsle med sur gjødsel'],5:['Blomstring'],8:['Høst'],9:['Høst resten']} },
  // ─────────────── FRUKT ───────────────
  { key:'eple',         name:'Epletre',      emoji:'🍎', cat:'frukt', harvest:true,  pricePerKg:25,
    seasonal:{3:['Beskjær treet'],4:['Gjødsle med frukttregjødsel'],5:['Tynn ut frukter etter blomstring'],7:['Sjekk for skurv'],8:['Høst tidlige sorter'],9:['Høst sene sorter'],10:['Rydde fallne epler']} },
  { key:'pære',         name:'Pæretre',      emoji:'🍐', cat:'frukt', harvest:true,  pricePerKg:30,
    seasonal:{3:['Beskjær'],4:['Gjødsle'],5:['Tynn ut frukter'],8:['Høst tidligsorter'],9:['Høst resten']} },
  { key:'plomme',       name:'Plommetre',    emoji:'🟣', cat:'frukt', harvest:true,  pricePerKg:35,
    seasonal:{3:['Beskjær etter frost-risiko'],4:['Gjødsle'],8:['Høst når myke og søte'],9:['Høst resten']} },
  { key:'kirsebær',     name:'Kirsebærtre',  emoji:'🍒', cat:'frukt', harvest:true,  pricePerKg:60,
    seasonal:{3:['Beskjær etter blomstring'],6:['Nett over for fugler'],7:['Høst hyppig'],8:['Gjødsle etter høsting']} },
  { key:'morello',      name:'Surkirsebær',  emoji:'🍒', cat:'frukt', harvest:true,  pricePerKg:50,
    seasonal:{3:['Beskjær'],7:['Høst'],8:['Gjødsle etter høsting']} },
  // ─────────────── URTER ───────────────
  { key:'basilikum',    name:'Basilikum',    emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:80,
    seasonal:{3:['Så innendørs'],5:['Plant ut'],6:['Klyp av topper og blomsterstilker'],7:['Høst regelmessig'],8:['Tørk eller frys ned']} },
  { key:'persille',     name:'Persille',     emoji:'🌾', cat:'urt', harvest:true,  pricePerKg:60,
    seasonal:{3:['Så innendørs'],5:['Plant ut'],6:['Høst regelmessig'],7:['Høst'],8:['Høst'],9:['Frys ned resten']} },
  { key:'timian',       name:'Timian',       emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:60,
    seasonal:{5:['Plant ut'],6:['Høst toppskudd'],7:['Tørk'],8:['Klipp tilbake etter blomstring']} },
  { key:'oregano',      name:'Oregano',      emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:60,
    seasonal:{5:['Plant ut'],7:['Høst rett før blomstring — mest aroma'],8:['Tørk bunter']} },
  { key:'rosmarin',     name:'Rosmarin',     emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:70,
    seasonal:{5:['Plant ut etter siste frost'],6:['Høst toppskudd'],10:['Bring inn eller dekk godt']} },
  { key:'mynthe',       name:'Mynte',        emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:50,
    seasonal:{4:['Plant i avgrenset beholder — sprer seg'],6:['Høst'],7:['Høst'],8:['Tørk']} },
  { key:'gressløk',     name:'Gressløk',     emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:40,
    seasonal:{4:['Første skudd'],5:['Høst med saks'],6:['Høst'],7:['Klipp ned etter blomstring'],8:['Høst igjen'],9:['Høst siste runde']} },
  { key:'dill',         name:'Dill',         emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:50,
    seasonal:{5:['Så direkte'],6:['Høst blader'],7:['Høst — trekker opp i varme'],8:['Samle frø']} },
  { key:'koriander',    name:'Koriander',    emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:60,
    seasonal:{5:['Så direkte, litt skygge'],6:['Høst blader'],7:['Samle frø']} },
  { key:'estragon',     name:'Estragon',     emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:70,
    seasonal:{5:['Plant ut'],6:['Høst toppskudd'],7:['Høst'],8:['Tørk']} },
  { key:'sitronmelisse',name:'Sitronmelisse',emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:50,
    seasonal:{5:['Plant ut'],6:['Høst'],7:['Høst'],8:['Tørk eller lag te']} },
  { key:'salvie',       name:'Salvie',       emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:60,
    seasonal:{5:['Plant ut'],6:['Høst toppskudd'],7:['Klipp etter blomstring'],10:['Dekk til i kalde strøk']} },
  { key:'kjørvel',      name:'Kjørvel',      emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:60,
    seasonal:{4:['Så direkte, halvskygge'],5:['Høst'],6:['Høst'],7:['Trekker opp — så ny runde']} },
  { key:'angelika',     name:'Angelika',     emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:40,
    seasonal:{4:['Første skudd'],5:['Høst unge stilker'],6:['Bruk blader og stilker'],8:['Samle frø']} },
  { key:'isop',         name:'Isop',         emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:50,
    seasonal:{5:['Plant ut'],7:['Høst og tørk'],8:['Klipp etter blomstring']} },
  { key:'merian',       name:'Merian',       emoji:'🌿', cat:'urt', harvest:true,  pricePerKg:55,
    seasonal:{5:['Plant ut'],7:['Høst rett før blomstring'],8:['Tørk']} },
  // ─────────────── ROSER ───────────────
  { key:'rose-hybrid',        name:'Hybridtearose',                    emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Fjern vinterbeskyttelse'],4:['Beskjær til 30-40 cm, 3-5 sunne knopper'],5:['Gjødsle med rosegjødsel'],6:['Kontroller for bladlus og svartflekk'],7:['Gjødsle igjen'],8:['Slutt å gjødsle'],10:['Dekk med granbar eller jord'],11:['Dekk til ved frost under -10°C']} },
  { key:'rose-hybrid-ingrid', name:'Hybridtearose "Ingrid Bergman"',   emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Fjern vinterbeskyttelse'],4:['Beskjær til 30-40 cm'],5:['Gjødsle'],6:['Kontroller for svartflekk'],7:['Gjødsle igjen'],8:['Slutt å gjødsle'],10:['Dekk foten godt']} },
  { key:'rose-hybrid-peace',  name:'Hybridtearose "Peace"',            emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Fjern vinterdekke'],4:['Beskjær moderat'],5:['Gjødsle'],6:['Gul/rosa blomstring'],7:['Gjødsle'],8:['Siste gjødsling'],10:['Dekk foten']} },
  { key:'rose-busk',          name:'Buskrose (generell)',               emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Fjern vinterbeskyttelse'],4:['Lett beskjæring'],5:['Gjødsle'],6:['Blomstring'],7:['Blomstring'],8:['Blomstring'],9:['Slutt å gjødsle'],10:['Dekk foten']} },
  { key:'rose-busk-knopp',    name:'Buskrose "Knock Out"',              emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{4:['Beskjær til 30 cm'],5:['Gjødsle sparsomt'],6:['Blomstring — sjeldent skurv'],7:['Blomstring'],8:['Blomstring'],9:['Blomstring'],10:['Dekk lett']} },
  { key:'rose-busk-carefree', name:'Buskrose "Carefree Wonder"',        emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{4:['Lett beskjæring'],5:['Gjødsle'],6:['Blomstring'],7:['Blomstring'],8:['Blomstring'],10:['Dekk foten']} },
  { key:'rose-busk-austin',   name:'Engelsk rose (David Austin)',       emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Fjern vinterbeskyttelse'],4:['Beskjær til 40-50 cm'],5:['Gjødsle med rosegjødsel'],6:['Duftende blomstring'],7:['Klipp visne for mer blomstring'],8:['Blomstring'],10:['Dekk godt']} },
  { key:'rose-klatre',        name:'Klatrerose (generell)',             emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Fjern skadde skudd'],4:['Fest nye skudd til gitter'],5:['Gjødsle'],6:['Første blomstring'],7:['Klipp visne blomster'],8:['Siste blomstring'],10:['Bind løse skudd'],11:['Dekk foten']} },
  { key:'rose-klatre-newdawn',name:'Klatrerose "New Dawn"',             emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Svært hardfør — minimal vinterbeskyttelse nødvendig'],4:['Fjern kun døde greiner'],5:['Gjødsle'],6:['Første kraftige blomstring — blekrosa'],7:['Klipp visne for ny runde'],8:['Repeter blomstring'],10:['Bind skudd til gitter']} },
  { key:'rose-klatre-zeph',   name:'Klatrerose "Zéphirine Drouhin"',   emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Fjern vinterbeskyttelse'],4:['Minimal beskjæring — tornfri sort'],5:['Gjødsle — gi god luftsirkulasjon'],6:['Dyp rosa, sterk duft'],7:['Klipp visne for ny blomstring'],8:['Repeter blomstring'],10:['Dekk foten']} },
  { key:'rose-klatre-super',  name:'Klatrerose "Super Excelsa"',        emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Tåler norsk vinter godt'],4:['Litt beskjæring'],5:['Gjødsle'],6:['Kraftig rødblomsring'],7:['Masser av blomster'],8:['Blomstring'],10:['Bind skudd']} },
  { key:'rose-klatre-aloha',  name:'Klatrerose "Aloha"',                emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Hardfør — god for Norge'],4:['Lett beskjæring'],5:['Gjødsle'],6:['Dyp rosarød blomstring — duftende'],7:['Klipp visne'],8:['Repeter blomstring'],10:['Dekk foten lett']} },
  { key:'rose-klatre-bobbie', name:'Klatrerose "Bobbie James"',         emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Kraftig — kan bli 8-10 m'],4:['Fjern kun skadde greiner'],5:['Gjødsle sparsomt'],6:['Hvit masseblomstring'],7:['Lett klipp for form'],9:['Nyper dannes'],10:['Bind skudd']} },
  { key:'rose-klatre-ghisl',  name:'Klatrerose "Ghislaine de Féligonde"',emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Relativt hardfør'],4:['Lett beskjæring'],5:['Gjødsle'],6:['Krem/gul masseblomstring'],7:['Klipp visne for ny runde'],8:['Repeter blomstring'],10:['Dekk foten']} },
  { key:'rose-parkrose',      name:'Parkrose',                          emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{4:['Beskjær lett om nødvendig'],5:['Gjødsle'],6:['Blomstring'],7:['Noen sorter blomstrer igjen'],9:['Nypefrukter modner'],10:['La nyper stå']} },
  { key:'rose-parkrose-comp', name:'Parkrose "Compassion"',             emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{3:['Fjern vinterbeskyttelse'],4:['Lett beskjæring'],5:['Gjødsle'],6:['Laksrosa, sterk duft'],7:['Klipp visne'],8:['Repeter blomstring'],10:['Dekk foten']} },
  { key:'rose-ville',         name:'Villrose (Rosa canina)',            emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{5:['Blomsterknopper'],6:['Enkel hvit/lyserosa blomstring'],9:['Plukk nyper til te og saft'],10:['La nyper stå for fugler']} },
  { key:'rose-minirose',      name:'Minirose / Patiorose',              emoji:'🌹', cat:'rose', harvest:false,
    seasonal:{4:['Flytt ut i lunt sted etter frost'],5:['Gjødsle ukentlig'],6:['Blomstring'],7:['Blomstring'],8:['Blomstring'],9:['Ta inn FØR frost'],10:['Overvint lyst og 5-10°C']} },
  // ─────────────── STAUDER ───────────────
  { key:'akeleie',      name:'Akeleie (Aquilegia)',              emoji:'💜', cat:'staude', harvest:false,
    seasonal:{4:['Første vekst'],5:['Blomstring'],6:['Blomstring — sår seg selv'],7:['La frøhoder stå'],3:['Klipp ned fjorårets stilker']} },
  { key:'astilbe',      name:'Astilbe (fjærpryds)',              emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{4:['Ny vekst — gjødsle'],6:['Blomstring'],7:['Blomstring'],10:['La frøhoder stå'],3:['Klipp ned']} },
  { key:'bergenia',     name:'Bergenia (elefantøre)',            emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{3:['Tidlig blomstring'],4:['Blomstring'],5:['Klipp bort stygge blader'],10:['Blader rødfarges i kulde']} },
  { key:'blåklokke',    name:'Blåklokke (Campanula)',            emoji:'💙', cat:'staude', harvest:false,
    seasonal:{5:['Blomstring starter'],6:['Blomstring'],7:['Klipp ned for høstblomstring'],9:['Høstblomstring mulig'],3:['Klipp ned til bakken']} },
  { key:'daglilje',     name:'Daglilje (Hemerocallis)',          emoji:'🌼', cat:'staude', harvest:false,
    seasonal:{4:['Første grønne vekst'],6:['Blomstring'],7:['Blomstring — lang sesong'],8:['Siste blomster'],3:['Klipp ned til 15 cm']} },
  { key:'echinacea',    name:'Solhat (Echinacea)',               emoji:'🌺', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut i sol'],7:['Blomstring'],8:['Blomstring'],9:['La frøhoder stå'],3:['Klipp ned']} },
  { key:'floks',        name:'Høstfloks (Phlox)',                emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{4:['Del klumper om nødvendig'],7:['Blomstring'],8:['Blomstring'],9:['Blomstring'],3:['Klipp ned']} },
  { key:'geranium',     name:'Storkenebb (Geranium)',            emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{4:['Første vekst'],6:['Blomstring'],7:['Klipp ned for ny runde'],8:['Ny blomstring'],3:['Klipp ned']} },
  { key:'hjerteskjell', name:'Hjerteskjell (Dicentra)',          emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{4:['Blomstring'],5:['Blomstring — vakre hjertformede blomster'],6:['Bladene gulner og forsvinner — normalt'],3:['Klipp ned']} },
  { key:'kattemynte',   name:'Kattemynte (Nepeta)',              emoji:'💜', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut'],6:['Blomstring'],7:['Klipp ned til halvparten for ny blomstring'],8:['Ny blomstring'],3:['Klipp ned til 10 cm']} },
  { key:'rudbeckia',    name:'Gullblomst (Rudbeckia)',           emoji:'🌻', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut i sol'],7:['Blomstring'],8:['Blomstring'],9:['Blomstring'],10:['La frøhoder stå'],3:['Klipp ned']} },
  { key:'ryllik',       name:'Ryllik (Achillea)',                emoji:'🌼', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut'],6:['Blomstring'],7:['Blomstring'],8:['Klipp ned for ny blomstring'],9:['Ny blomstring'],3:['Klipp ned']} },
  { key:'salvia-nem',   name:'Præriesalvia (Salvia nemorosa)',   emoji:'💙', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut i full sol'],6:['Blomstring'],7:['Klipp ned for ny blomstring'],8:['Ny blomstring'],3:['Klipp ned']} },
  { key:'sedum',        name:'Bergknapp (Sedum/Hylotelephium)',  emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{4:['Første vekst'],8:['Blomstring'],9:['Blomstring'],10:['La frøhoder stå til vår'],3:['Klipp ned']} },
  { key:'trollius',     name:'Ballblom (Trollius)',              emoji:'🌼', cat:'staude', harvest:false,
    seasonal:{4:['Første vekst'],5:['Blomstring'],6:['Klipp ned for ny runde'],8:['Ny blomstring'],3:['Klipp ned']} },
  { key:'valmue',       name:'Orientalsk valmue (Papaver)',      emoji:'🌺', cat:'staude', harvest:false,
    seasonal:{4:['Første vekst'],5:['Blomstring'],6:['Bladene forsvinner — normalt'],9:['Ny vekst starter']} },
  { key:'monarda',      name:'Bergmynte (Monarda)',              emoji:'🌺', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut'],7:['Blomstring'],8:['Blomstring'],3:['Del klumper']} },
  { key:'anemone-jap',  name:'Japansk anemone',                  emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{8:['Blomstring'],9:['Blomstring'],10:['Klipp ned'],3:['Unngå å flytte']} },
  { key:'helenium',     name:'Høstsolblomst (Helenium)',         emoji:'🌻', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut'],7:['Klyp av topp for busket vekst'],8:['Blomstring'],9:['Blomstring'],3:['Klipp ned']} },
  { key:'heuchera',     name:'Korallklokke (Heuchera)',          emoji:'🌿', cat:'staude', harvest:false,
    seasonal:{4:['Ny vekst'],6:['Blomsterstilker'],3:['Del klumper hvert 3-4 år'],10:['Mulch over røttene']} },
  { key:'hostas',       name:'Hostas (funkia)',                  emoji:'🌿', cat:'staude', harvest:false,
    seasonal:{4:['Skudd kommer — beskytt mot snegl'],6:['Full løvverk'],10:['Klipp ned'],11:['Mulch over roten']} },
  { key:'astrantia',    name:'Stjerneskjerm (Astrantia)',        emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut i halvskygge'],6:['Blomstring'],7:['Klipp ned for ny runde'],8:['Ny blomstring'],3:['Klipp ned']} },
  { key:'liatris',      name:'Risblomst (Liatris)',              emoji:'💜', cat:'staude', harvest:false,
    seasonal:{5:['Plant løk/rotklump'],7:['Blomstring'],8:['Blomstring'],3:['La stå til vår']} },
  { key:'persicaria',   name:'Høstpryds (Persicaria)',           emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{4:['Rask vekst'],6:['Blomstring'],7:['Blomstring'],8:['Blomstring'],3:['Klipp ned og del om nødvendig']} },
  { key:'solidago',     name:'Gullris (Solidago)',               emoji:'🌼', cat:'staude', harvest:false,
    seasonal:{8:['Blomstring'],9:['Gul høstblomstring'],3:['Klipp ned']} },
  { key:'kniphofia',    name:'Fakkellilje (Kniphofia)',          emoji:'🔴', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut i godt drenert jord'],7:['Blomstring'],8:['Blomstring'],10:['Dekk over med halm'],3:['Fjern vinterdekke']} },
  { key:'sidalcea',     name:'Præriekattost (Sidalcea)',         emoji:'🌸', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut'],6:['Blomstring'],7:['Klipp ned for ny runde'],8:['Ny blomstring'],3:['Klipp ned']} },
  { key:'scabiosa',     name:'Skorsoneurt (Scabiosa)',           emoji:'💜', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut'],6:['Blomstring'],7:['Blomstring'],8:['Blomstring'],3:['Klipp ned']} },
  { key:'stachys',      name:'Ullugle (Stachys)',                emoji:'🌿', cat:'staude', harvest:false,
    seasonal:{5:['Grå, ull-myke blader'],6:['Blomsterstilker'],7:['Klipp ned stilker etter blomstring'],3:['Klipp ned og del']} },
  { key:'primula',      name:'Nøkleblom (Primula)',              emoji:'🌼', cat:'staude', harvest:false,
    seasonal:{3:['Blomstrer tidlig'],4:['Blomstring'],5:['Blomstring'],8:['Del og replant']} },
  { key:'crocosmia',    name:'Montbretia (Crocosmia)',           emoji:'🔴', cat:'staude', harvest:false,
    seasonal:{5:['Plant kormoller'],7:['Blomstring'],8:['Blomstring'],10:['Dekk med mulch'],3:['Del om nødvendig']} },
  { key:'verbena-bon',  name:'Jernurt (Verbena bonariensis)',    emoji:'💜', cat:'staude', harvest:false,
    seasonal:{5:['Så eller plant ut'],7:['Blomstring'],8:['Blomstring'],9:['Blomstring'],10:['La stå — sår seg selv']} },
  { key:'veronica',     name:'Ærenpris (Veronica)',              emoji:'💙', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut'],6:['Blomstring'],7:['Klipp ned for ny blomstring'],8:['Ny blomstring'],3:['Klipp ned']} },
  { key:'inula',        name:'Alantblomst (Inula)',              emoji:'🌼', cat:'staude', harvest:false,
    seasonal:{5:['Plant ut i sol'],7:['Blomstring'],8:['Blomstring'],3:['Klipp ned']} },
  { key:'ligularia',    name:'Gyldenlak (Ligularia)',            emoji:'🌿', cat:'staude', harvest:false,
    seasonal:{4:['Trenger fuktig og halvskygge'],7:['Blomstring'],8:['Blomstring'],3:['Klipp ned']} },
  // ─────────────── BUSKER ───────────────
  { key:'rhododendron',     name:'Rhododendron',          emoji:'🌸', cat:'busk', harvest:false,
    seasonal:{3:['Gjødsle med sur rhododendrongjødsel (pH 4-5)'],5:['Blomstring'],6:['Bryt av visne blomsterstander'],7:['Vann godt i tørke'],10:['Dekk unge planter med granbar']} },
  { key:'azalea',           name:'Azalea (hage)',          emoji:'🌸', cat:'busk', harvest:false,
    seasonal:{3:['Gjødsle med sur gjødsel'],4:['Tidligst blomstrende'],5:['Blomstring'],6:['Bryt av visne blomster'],10:['Dekk unge planter']} },
  { key:'syrin',            name:'Syrin',                  emoji:'💜', cat:'busk', harvest:false,
    seasonal:{4:['Blomsterknopper sveller'],5:['Blomstring'],6:['Klipp av visne blomsterstander rett etter blomstring']} },
  { key:'forsythia',        name:'Forsythia (Gullregn)',   emoji:'🌼', cat:'busk', harvest:false,
    seasonal:{3:['Beskjær etter blomstring'],4:['Blomstrer på bar kvist'],5:['Løv kommer etter blomstring'],6:['Lett klipp for form']} },
  { key:'spirea',           name:'Spirea',                 emoji:'🌸', cat:'busk', harvest:false,
    seasonal:{4:['Hvit blomstring (tidligspirea)'],5:['Blomstring'],6:['Klipp ned etter blomstring']} },
  { key:'blåregn',          name:'Blåregn (Wisteria)',     emoji:'💜', cat:'busk', harvest:false,
    seasonal:{4:['Blomstring på 2-3 år gamle greiner'],5:['Blomstring'],6:['Klipp sommerranker til 6 blader'],8:['Klipp igjen til 2-3 blader'],2:['Vinterbeskjæring til 2-3 knopper']} },
  { key:'klematis',         name:'Klematis',               emoji:'💜', cat:'busk', harvest:false,
    seasonal:{4:['Beskjær etter gruppe (se info)'],5:['Gjødsle med kaliumrik gjødsel'],6:['Blomstring (avhengig av sort)'],7:['Blomstring'],8:['Blomstring gruppe 3'],10:['Dekk røttene']} },
  { key:'klematis-gruppe1', name:'Klematis gr.1 (alpina)', emoji:'💜', cat:'busk', harvest:false,
    seasonal:{4:['Blomstring på fjorårets skudd'],5:['Blomstring — aldri klipp nå'],6:['Minimalt stell'],7:['Kun forsiktig opprydding']} },
  { key:'klematis-gruppe3', name:'Klematis gr.3 (jackmanii)',emoji:'💜', cat:'busk', harvest:false,
    seasonal:{2:['Klipp ned til 30-50 cm'],3:['Gjødsle etter beskjæring'],6:['Blomstring fra midsommer'],7:['Blomstring'],8:['Blomstring'],9:['Siste blomstring']} },
  { key:'hortensia',        name:'Hortensia',              emoji:'💐', cat:'busk', harvest:false,
    seasonal:{3:['Forsiktig beskjæring — kun tørt og dødved'],4:['Gjødsle'],8:['Blomstring'],9:['Blomstring'],10:['La blomsterstander stå til vår']} },
  { key:'hortensia-klatre', name:'Klatre-hortensia',       emoji:'💐', cat:'busk', harvest:false,
    seasonal:{4:['Fest til vegg'],5:['Gjødsle'],6:['Blomstring'],7:['Klipp lett etter blomstring']} },
  // ─────────────── TRÆR ───────────────
  { key:'magnolia',     name:'Magnolia',   emoji:'🌸', cat:'tre', harvest:false,
    seasonal:{4:['Blomstring på bar kvist'],5:['Løv kommer etter blomstring'],3:['Unngå beskjæring — sår gror dårlig']} },
  { key:'hengepil',     name:'Hengepil',   emoji:'🌳', cat:'tre', harvest:false,
    seasonal:{4:['Første blader'],6:['Trives ved vann'],9:['Gulfarging'],10:['Beskjær unge trær for form']} },
  { key:'bjørketre',    name:'Bjørk',      emoji:'🌳', cat:'tre', harvest:false,
    seasonal:{4:['Bladsprett'],9:['Gul høstfarge'],10:['Beskjær i dvale']} },
  // ─────────────── PRYDPLANTER ───────────────
  { key:'lavendel',     name:'Lavendel',             emoji:'💜', cat:'prydplante', harvest:false,
    seasonal:{4:['Lett klipp av fjorårets stilker'],7:['Klipp tilbake etter blomstring — aldri ned i gammelt trevirke'],11:['Dekk med granbar i kalde strøk']} },
  { key:'solsikke',     name:'Solsikke',             emoji:'🌻', cat:'prydplante', harvest:false,
    seasonal:{5:['Så direkte utendørs etter siste frost'],6:['Tynn ut til 30-50 cm avstand'],8:['Bind opp om nødvendig'],9:['La hoder stå som fuglemat']} },
  { key:'peon',         name:'Peon',                 emoji:'🌸', cat:'prydplante', harvest:false,
    seasonal:{4:['Første skudd'],5:['Støtt opp'],6:['Blomstring'],7:['Klipp ned stilker etter blomstring'],10:['Klipp ned til bakken']} },
  { key:'iris',         name:'Iris (skjeggfri)',      emoji:'💜', cat:'prydplante', harvest:false,
    seasonal:{4:['Nye skudd'],5:['Blomstring'],6:['Klipp av visne blomster'],8:['Del og replant store klumper']} },
  { key:'iris-skjegg',  name:'Iris (skjeggete)',      emoji:'💜', cat:'prydplante', harvest:false,
    seasonal:{4:['Ny vekst'],6:['Blomstring'],7:['Del klumper, tørk rhizom i sol'],8:['Plant med 50% av rhizom over jord']} },
  { key:'tulipan',      name:'Tulipan',               emoji:'🌷', cat:'prydplante', harvest:false,
    seasonal:{9:['Plant løk 15-20 cm dypt'],10:['Plant til midten av oktober'],4:['Blomstring'],5:['La bladene gule naturlig — 6 uker'],6:['Ta opp løk og lagre tørt']} },
  { key:'georgine',     name:'Georgine',              emoji:'🌸', cat:'prydplante', harvest:false,
    seasonal:{5:['Plant ut etter siste frost'],6:['Klyp av topp'],7:['Blomstring'],8:['Blomstring'],9:['Siste blomstring'],10:['Ta opp knollene etter første frost, tørk og lagre']} },
  { key:'luppiner',     name:'Luppiner',              emoji:'💐', cat:'prydplante', harvest:false,
    seasonal:{5:['Så eller plant ut'],6:['Blomstring'],7:['Klipp av visne stilker for ny blomstring'],8:['Ny blomstring mulig']} },
  { key:'ridderspore',  name:'Ridderspore (Delphinium)',emoji:'💙', cat:'prydplante', harvest:false,
    seasonal:{5:['Plant ut'],6:['Blomstring — opp til 2 m høy'],7:['Klipp ned til 30 cm for høstblomstring'],9:['Høstblomstring']} },
  { key:'pelargonium',  name:'Pelargonium',            emoji:'🌸', cat:'prydplante', harvest:false,
    seasonal:{5:['Sett ut etter frost'],6:['Gjødsle ukentlig'],7:['Blomstring'],8:['Blomstring'],9:['Ta inn FØR frost'],10:['Overvint lyst og kjølig']} },
  { key:'påskelilje',   name:'Påskelilje (Narcissus)', emoji:'🌼', cat:'prydplante', harvest:false,
    seasonal:{9:['Plant løk 10-15 cm dypt'],3:['Viser seg tidlig'],4:['Blomstring'],5:['La bladene gule 6 uker']} },
  { key:'krokus',       name:'Krokus',                 emoji:'🌷', cat:'prydplante', harvest:false,
    seasonal:{9:['Plant løk 5-8 cm dypt'],3:['Blomstrer tidligst av alle løkblomster'],4:['La blader gule naturlig']} },
  { key:'hyasint',      name:'Hyasint',                emoji:'💜', cat:'prydplante', harvest:false,
    seasonal:{9:['Plant løk 15 cm dypt'],4:['Blomstring — sterk duft'],5:['La blader gule naturlig']} },
  { key:'fuchsia',      name:'Fuchsia',                emoji:'💜', cat:'prydplante', harvest:false,
    seasonal:{5:['Sett ut etter frost'],6:['Gjødsle ukentlig'],7:['Blomstring'],8:['Blomstring'],9:['Ta inn FØR frost'],10:['Overvint mørkt og 5-8°C']} },
]

// ────────────────────────────────────────────────
// Plantebeskrivelser
// ────────────────────────────────────────────────
export function plantDesc(key) {
  const descs = {
    tomat: 'Tomat (Solanum lycopersicum) er den mest populære hagefrukten i Norge og krever varm sommer. Dyrkes best i drivhus eller mot sydvendt vegg. Fjern sideskudd regelmessig (indeterminate sorter) for å konsentrere energi til fruktsetting. Vann jevnt — ujevn vanning gir blomsterendeåte (BER). Gjødsle ukentlig med tomatgjødsel fra blomstring.',
    agurk: 'Agurk (Cucumis sativus) er enda mer varmekrevende enn tomat og bør dyrkes i drivhus i Norge. Klyp av toppen ved 50 cm for å fremme sideskudd. Høst mens frukten er ung — store agurker hemmer ny fruktsetting.',
    gulrot: 'Gulrot (Daucus carota) trives i dyp, løs, steinfattig jord. Tynn ut til 5 cm tidlig. Tåler lett frost og kan stå i bakken langt utover høsten — frost gir søtere smak. Rotflue er den største trusselen — bruk fiberduk som forebygging.',
    potet: 'Potet (Solanum tuberosum) er en av de mest produktive hagevekstene. Hypp opp jord to ganger for bedre avling og for å hindre grønne poteter. Tørråte (Phytophthora) er den alvorligste sykdommen — overvåk bladene fra juli.',
    gresskar: 'Gresskar (Cucurbita) er storvokst og plasskrevenende men enkel å dyrke. La bare 2-3 frukter per plante utvikle seg. Skallet skal være hardt og stilken tørr og korkaktig ved høsting. Lagres kjølig og tørt i 3-4 måneder.',
    løk: 'Løk (Allium cepa) er enkel fra sett. Slutt å gjødsle fra juli. Høst når 50% av toppene har falt over. Tørk grundig i 2-3 uker før lagring i tørt, kjølig rom.',
    hvitløk: 'Hvitløk (Allium sativum) plantes om høsten og gir avling neste sommer. Fjern blomsterstilker i juni for større løk. Høst når de to nederste bladlagene er gule.',
    purre: 'Purre (Allium porrum) kan høstes langt ut i november og tåler frost. Hypp opp jord rundt stilken for å bleke. Noen sorter kan overvintre.',
    brokkoli: 'Brokkoli (Brassica oleracea) krever mye nitrogen og jevn fuktighet. Høst hoved-hodet mens blomsterknopper er tette og grønne. Etter høsting gir planten mange sideskudd i uker fremover.',
    blomkål: 'Blomkål er mer krevende enn brokkoli. Bind bladene over hodet for å bevare hvitfargen. Høst når hodet er fast, hvitt og kompakt.',
    hodekål: 'Hodekål kan sprekke ved plutselig mye vann etter tørke — vann jevnt. Hvit- og rødkål er gode lagringsgrønnsaker og holder seg kjølig i måneder.',
    rosenkål: 'Rosenkål smaken forbedres etter frost. Høst neden-fra-og-opp ettersom spirene modner fra bunnen. Trenger lang vekstsesong.',
    spinat: 'Spinat (Spinacia oleracea) trekker opp i varme. Sår du i april høster du i mai-juni. Ny sårunde i august for høstspinaten.',
    salat: 'Salat (Lactuca sativa) er en av de raskeste hagevekstene. Kan sås i vinduskarm fra mars. Høst ytterblader kontinuerlig på bladsorter. Bolter i sterk varme.',
    paprika: 'Paprika (Capsicum annuum) passer best i drivhus i Norge. Trenger lang vekstsesong — sow innendørs i januar-februar. Grønn paprika er umodne frukter, rød/gul er modne.',
    squash: 'Squash (Cucurbita pepo) er svært produktiv. Høst mens frukten er ung (15-20 cm) for best smak. Utnøstede frukter vokser til kjempestore courgetter og stopper ny fruktsetting.',
    bønner: 'Bønner (Phaseolus vulgaris) frigjør nitrogen til jorda. Klatrebønner trenger støtte. Høst hyppig — bønnene skal være unge og sprø.',
    erter: 'Erter (Pisum sativum) er blant de aller tidligste sommergrønnsakene. Høst daglig — erter som henger for lenge blir seige.',
    rødbete: 'Rødbete (Beta vulgaris) er enkel og næringsrik. Hele planten er spiselig — bladene som salat. Baby-rødbeter etter 6-7 uker er en delikatesse.',
    pastinakk: 'Pastinakk (Pastinaca sativa) smaken forbedres etter frost. En av de beste lagringsgrønnsakene fra hagen.',
    kålrabi: 'Kålrabi (Brassica oleracea gongylodes) klar på 6-8 uker. Spis bulben ung (6-8 cm) — den blir treaktig om den blir for stor.',
    reddik: 'Reddik (Raphanus sativus) er den raskeste hageveksten — klar på 3-4 uker fra såing. Perfekt for å fylle tomme rader mellom saktevoksende kulturer.',
    mais: 'Mais (Zea mays) trenger varme og sol. Plant i blokk (4x4) for god vindbestøvning. Høst når silkehårene er brune. Mais bør ideelt fra plante til kjele på under 30 minutter.',
    mangold: 'Mangold (Beta vulgaris cicla) tåler varme bedre enn spinat og produserer gjennom hele sommeren. Bladstilkene kommer i rødt, gult og hvitt.',
    asparges: 'Asparges (Asparagus officinalis) — venter 3 år på første høsting, men planten gir i 20 år. Ikke høst de to første årene. Fra år 3: høst i 4-6 uker, la deretter bregnen vokse.',
    rabarbra: 'Rabarbra (Rheum rhabarbarum) er en av de tidligste høstene fra hagen. Kun stilkene er spiselige — bladene er giftige. La aldri mer enn 1/3 av stilkene høstes av gangen.',
    fennikel: 'Fennikel (Foeniculum vulgare) krever varmt vær for å danne ordentlig bulb. Hypp opp jord rundt bulben for å bleke. Trekker opp lett i kaldt og tørt vær.',
    stangselleri: 'Stangselleri (Apium graveolens) er krevende men belønner deg med saftige stilker. Trenger mye vann og næring. Hvit selleriet ved å dekke stilkene de siste ukene.',
    kinakål: 'Kinakål (Brassica rapa pekinensis) bolter lett i varme. Sår du i høysommer (juli) unngår du problemet. Perfekt til wok og kimchi.',
    jordbær: 'Jordbær (Fragaria x ananassa) er blant de mest populære og enkle hagevekstene. Fjern utløpere løpende for å holde energien i fruktsettingen. Bytt ut planter hvert 3-4 år. Jordbærhalm under frukten holder den ren og tørr.',
    bringebær: 'Bringebær (Rubus idaeus) er svært produktivt men sprer seg aggressivt. Plant langs gjerde. Sommersorter bærer på fjorårets skudd — klipp disse ned etter høsting.',
    solbær: 'Solbær (Ribes nigrum) er ekstremt næringsrik (mye C-vitamin). Tåler halvskygge. Beskjær eldre grener for å forny busken. God til saft, syltetøy og frysing.',
    'rips-rød': 'Rød rips (Ribes rubrum) er hardfør og tåler mer skygge enn de fleste bærbusker. De sure røde bærene er rike på pektin og perfekt til gelé og saft.',
    'rips-hvit': 'Hvit rips er en variant av rød rips med mildere, søtere bær. Brukes på samme måte. Fin som delikatesse direkte fra busken.',
    stikkelsbær: 'Stikkelsbær (Ribes uva-crispa) er hardføre og produktive. Umodne grønne bær er syrlige og gode til syltetøy; modne bær er søtere. Mjøldogg er den vanligste sykdommen.',
    bjørnebær: 'Bjørnebær (Rubus fruticosus) er kraftig voksende og krever støtte. Fruktene er store og saftrike. Blomstrer og bærer på toårsskudd som bringebær.',
    aronia: 'Aronia (svartsurbær) er svært hardfør og full av antioksidanter. Bærene er bitre ferske men sødmer etter frost. Best til saft, te og tørking.',
    blåbær: 'Hageblåbær (Vaccinium corymbosum) krever sur jord (pH 4-5). Nett er nærmest obligatorisk mot fugler. Krever kryssbefruktning — plasser minst to sorter nær hverandre. Svært langlivet.',
    hyllebær: 'Hyllebær (Sambucus nigra) er rask-voksende. Hvite blomster i juni til hyldeblomstsaft. Svarte bær i september til saft og syltetøy — ikke spis rå.',
    tyttebær: 'Tyttebær (Vaccinium vitis-idaea) krever sur jord som blåbær. De røde bærene brukes til syltetøy, saft og som tilbehør til kjøtt. Svært langlivet.',
    eple: 'Epletre (Malus domestica) er en av de beste investeringene i hagen. To sorter gir bedre pollinering. Norske sorter som Aroma, Gravenstein og Discovery er hardføre. Beskjær hvert år for god fruktkvalitet. Skurv er den vanligste sykdommen — velg resistente sorter som Topaz.',
    pære: 'Pæretre (Pyrus communis) ligner eple men er noe mer varmekrevende. Conference er mest hardfør og selvfruktbar. Pærer høstes umodne og modnes innendørs. Lagres kjølig.',
    plomme: 'Plommetre (Prunus domestica) er relativt lett å dyrke i norsk klima. Victoriapl omme er den mest populære sorten. Beskjær etter frost-risiko er over.',
    kirsebær: 'Kirsebærtre (Prunus avium) blomstrer vakkert om våren. Netting er nesten obligatorisk — fuglene konkurrerer om bærene.',
    morello: 'Surkirsebær/Morello (Prunus cerasus) er hardere enn søtkirsebær og selvfruktbar. Bærene er utmerkede til saft, syltetøy og likør. Tåler halvskygge.',
    basilikum: 'Basilikum (Ocimum basilicum) er en varme-elsker. Klyp av blomsterstilker kontinuerlig. Søt basilikum er den klassiske sorten; thai-basilikum har mer anis-smak.',
    persille: 'Persille (Petroselinum crispum) spirer sakte (3-4 uker) — bløtlegg frøene i vann natten over. Flatbladpersille er kraftigere og bedre til matlaging. Tåler frost til november.',
    timian: 'Timian (Thymus vulgaris) er en flerårig urt som tåler tørke godt. Klipp tilbake etter blomstring. Kan overvintre ute i sone 5-6 med litt beskyttelse.',
    oregano: 'Oregano (Origanum vulgare) kan overvintre ute. Smaken er sterkest rett før blomstring. Tørking intensiverer den karakteristiske mediterrane aromaen.',
    rosmarin: 'Rosmarin (Salvia rosmarinus) er klimafølsom i Norge. Fuktighet om vinteren dreper den lettere enn kulde. Bring inn i gryte om høsten eller dekk godt med granbar.',
    mynthe: 'Mynte (Mentha) vokser svært aggressivt. Plant ALLTID i gryte eller beholder — ellers tar den over hele bedet. Mange varianter: peppermynte, grønnmynte, marokansk mynte.',
    gressløk: 'Gressløk (Allium schoenoprasum) er den hardeste og enkleste urten. Blomstene i juni er vakre og spiselige. En av de aller første urtene å komme opp om våren.',
    'rose-hybrid': 'Hybridtearoser er de klassiske store enkeltblomsterne. Krever mer stell enn busk- og parkroser. Beskjær kraftig om våren (til 30-40 cm). Vann ved roten — aldri over bladene.',
    'rose-hybrid-ingrid': '"Ingrid Bergman" er en klassisk hybridtearose med dype fløyelrøde blomster. En av de mest populære norske roser. Remonterende. Relativt god motstandsdyktighet mot svartflekk.',
    'rose-hybrid-peace': '"Peace" er en av verdens mest kjente roser. Store krem-gule blomster med rosa kant. Kraftigvoksende sort. Har eksistert siden 1945. Moderat motstandsdyktighet mot sykdom.',
    'rose-busk': 'Buskroser er generelt hardiere og mindre krevende enn hybridtearoser. Blomstrer rikelig uten den intensive beskjæringen. Mange sorter er remonterende.',
    'rose-busk-austin': 'David Austin-roser kombinerer gammeldags blomsterform og duft med moderne remonterende egenskaper. Beskjær til 40-50 cm om våren. Noen sorter er noe sarte i norsk klima.',
    'rose-klatre': 'Klatreroser brukes mot vegger, gitter og pergola. De fleste blomstrer på gammel ved og tåler ikke kraftig beskjæring. Fest skudd horisontalt for mer blomstring.',
    'rose-klatre-newdawn': '"New Dawn" er en av de hardeste klatrerosene for norsk klima. Blekrosa, duftende blomster. Kan bli svært stor (6-8 m). Remonterende. Tåler halvskygge.',
    'rose-klatre-zeph': '"Zéphirine Drouhin" er tornfri, noe som gjør den enkel å jobbe med. Dyp rosa blomster med sterk duft. Remonterende. Noe sensitiv for svartflekk — gi god luftsirkulasjon.',
    'rose-parkrose': 'Parkroser er blant de hardeste rosene — mange utviklet spesielt for skandinavisk klima. Lite sykdomsproblemer. Mange danner vakre nyper om høsten.',
    'rose-ville': 'Villrose (Rosa canina) er den hardeste av alle roser og krever nesten ingen stell. De røde nypene er rike på C-vitamin og brukes til te, saft og syltetøy.',
    akeleie: 'Akeleie (Aquilegia) er en elegant staude med unike sporede blomster. Halvskyggetolererende. Kortlivet (2-3 år) men sår seg fritt og er alltid tilstede i hagen.',
    astilbe: 'Astilbe er perfekt for fuktige skygge- og halvskyggesteder. Fjærformede blomstertopper. Krever aldri tørke. La frøhodene stå om vinteren — de er dekorative med frost.',
    bergenia: 'Bergenia (elefantøre) er en nøysom, vintergrønn staude. Tidlig blomstring i mars-april. Tåler tørke, skygge og kald vinter. En av de mest hardføre staudene.',
    blåklokke: 'Blåklokke (Campanula) finnes i mange former. Blomstrer lenge (juni-august). Klipp ned etter blomstring for ny runde. Noen sorter sprer seg aggressivt.',
    daglilje: 'Daglilje (Hemerocallis) er en nøysom, robust staude. Hver enkelt blomst varer bare én dag, men planten produserer en blomst etter en annen i uker. Finnes i et enormt fargespekter.',
    echinacea: 'Solhat (Echinacea purpurea) har rosa blomster og konisk midtblomst. Trekker bier og sommerfugler. La frøhodene stå gjennom vinteren — fuglene spiser frøene. Meget hardfør.',
    floks: 'Høstfloks (Phlox paniculata) blomstrer fra juli til september med store duftende blomsterskjermer. Mjøldogg kan være et problem — velg resistente sorter.',
    geranium: 'Storkenebb (Geranium) er enkel og blomsterrik. Klipp ned etter blomstring for ny runde. Mange sorter er svært hardføre. Ikke forveksle med Pelargonium (balkong-"geranium").',
    sedum: 'Bergknapp (Sedum/Hylotelephium) er en kraftig høstblomstrende staude. Blomstrer august-oktober og trekker insekter. Ekstremt tørketålende. La blomsterstandene stå til vår.',
    hostas: 'Hostas (funkia) er skyggehagens dronning. Bladene er dens styrke i grønne, blå-grå eller gule farger. Perfekt under trær. Snegl elsker de saftige bladene — sett ut sneglefeller tidlig vår.',
    rudbeckia: 'Gullblomst (Rudbeckia) er en pålitelig høstblomstrende staude med gule blomster. Blomstrer fra juli til frost. Trekker insekter. Sår seg gjerne selv i hagen.',
    kattemynte: 'Kattemynte (Nepeta) er en myk, duftende staude med blå-lilla blomsterstander. Blomstrer lenge, klipp ned ved halvtid for ny runde. Katter kan bli overdrevent begeistret.',
    rhododendron: 'Rhododendron trenger sur jord (pH 4,5-5,5), halvskygge og jevn fuktighet. Grunt rotsystem — dekk med surt bark. Bryt av visne blomsterstander etter blomstring. Unngå gjødsel med kalk.',
    azalea: 'Hagezalea er nær beslektet med rhododendron og trenger sur jord og halvskygge. Blomstrer tidlig og intenst. Dekk med granbar om vinteren de første årene.',
    syrin: 'Syrin (Syringa) blomstrer i mai med karakteristisk sterk duft. Klipp av visne blomsterstander rett etter blomstring. Beskjær aldri i høst eller vinter.',
    forsythia: 'Forsythia (gullregn) er en av de første buskene til å blomstre — gule blomster på bar kvist i april. Beskjær rett etter blomstring (aldri om høsten). Svært hardfør.',
    hortensia: 'Hortensia (Hydrangea) er populær for de store blomsterhodene. Bigleaf-hortensia blomstrer på gammelt ved og beskjæres minimalt. PeeGee og Annabelle kan kuttes ned om høsten. Blomstfargen på bigleaf påvirkes av jordsurheten.',
    klematis: 'Klematis finnes i tre grupper med ulik beskjæringstid. Gruppe 1 (alpina): minimal beskjæring, blomstrer på gammel ved. Gruppe 2 (store hybridblomster): lett beskjæring. Gruppe 3 (jackmanii): kuttes ned til 30-50 cm hvert år. Dekk røttene godt.',
    'klematis-gruppe1': 'Klematis gruppe 1 (alpina, macropetala) blomstrer på fjorårets skudd i april-mai. Aldri kraftig beskjær — da mister du blomstringen.',
    'klematis-gruppe3': 'Klematis gruppe 3 (jackmanii, viticella) blomstrer på årets nye skudd fra midsommer. Kuttes ned til 30-50 cm hvert år i februar-mars.',
    blåregn: 'Blåregn (Wisteria) er spektakulær men krevende. Bruker 3-5 år på å etablere seg. To beskjæringer per år er nødvendig. Tålmodig eier belønnes med en av havens vakreste blomstringer.',
    spirea: 'Spirea er en nøysom, hardfør busk som blomstrer rikelig. Hvitblomstrende tidligsorter klippes etter blomstring om sommeren. Lite skadedyrproblemer.',
    magnolia: 'Magnolia blomstrer vakkert tidlig vår på bar kvist, men blomstene er svært frostømfintlige. Velg sen-blomstrende sorter i kalde strøk. Unngå beskjæring — magnolia gror sår dårlig.',
    hengepil: 'Hengepil (Salix x chrysocoma) trives best ved vann og i fuktig jord. Rask vekst — kan bli 8-12 m. Røttene kan skade avløpsrør. Plasser ikke nær rørinstallasjoner.',
    bjørketre: 'Bjørk (Betula) er et norsk ikontre med karakteristisk hvit bark. Bjørkepollen er en sterk allergenkilde i april-mai. Saften kan tappes i april.',
    lavendel: 'Lavendel (Lavandula angustifolia) er tørketålende og trives i mager, godt drenert jord og full sol. Klipp tilbake med 1/3 etter blomstring. Kritisk: aldri klipp ned i gammelt trevirke — den kommer ikke tilbake.',
    solsikke: 'Solsikke (Helianthus annuus) er en rask og enkel ettårsblomst. Sår direkte utendørs etter siste frost. Gigantsorter trenger støtte. La modne hoder stå — fuglene elsker frøene.',
    peon: 'Peon (Paeonia lactiflora) er langlivet med overdådige duftende blomster. Blomstrer i juni. Ikke plant for dypt — øynene skal være 2-3 cm under bakken. Kan stå på samme sted i tiår.',
    tulipan: 'Tulipan (Tulipa) plantes om høsten. La bladene gule naturlig i minst 6 uker etter blomstring. Nye løk hvert år gir rikest blomstring.',
    georgine: 'Georgine (Dahlia) er en luksusblomst med enormt fargespekter. Ta opp knollene etter første frost, tørk og lagre frostfritt. Gjødsle rikelig for best blomstring.',
    luppiner: 'Lupin er en spektakulær staude med fargerike blomsterstøyler. Kortlivet (3-5 år) men sår seg selv. Fixerer nitrogen i jorda. Pass på luseangrep i mai-juni.',
    pelargonium: 'Pelargonium (balkonggran) tåler ikke frost. Sett ut etter 15. mai. Gjødsle ukentlig. Ta inn i september. Overvintres lyst og kjølig (10-15°C).',
    påskelilje: 'Påskelilje (Narcissus) er en av de hardeste løkblomstene. La bladene stå og gule naturlig i minst 6 uker etter blomstring. Giftig for dyr.',
    krokus: 'Krokus er en av de første vårblomstene — dukker opp allerede i februar-mars. Særdeles effektiv i store grupper. Naturaliserer seg godt i gresset.',
    hyasint: 'Hyasint har usedvanlig sterk og behagelig duft. Kan dyrkes innendørs i spesialglass med bare vann for blomstring til jul.',
    fuchsia: 'Fuchsia er en elegant halvskyggeblomst. Tåler ikke frost — ta inn i september. Overvinter mørkt og kjølig (5-8°C). Klipp tilbake til 1/3 i mars.',
    ridderspore: 'Ridderspore (Delphinium) er en av hagenes mest dramatiske planter. Kan nå 2 m. Trenger støtte mot vind. Klipp ned til 30 cm etter første blomstring for høstblomstring.',
    iris: 'Iris (skjeggfri, Iris sibirica m.fl.) er en robust staude med elegante blomster. Trives i fuktig til normal jord. Del klumper hvert 4-5 år.',
    'iris-skjegg': 'Skjeggete iris (Iris germanica) trenger godt drenert jord og full sol. Rhizomene skal ligge halvt over jordoverflaten for å modnes i sol.',
  }
  return descs[key] || 'En plante som trives godt i norske hager med riktig stell og plassering.'
}

// ────────────────────────────────────────────────
// Hjelpefunksjoner
// ────────────────────────────────────────────────
export const PLANT_MAP = Object.fromEntries(PLANT_DB.map(p => [p.key, p]))

export function getPlant(key) {
  return PLANT_MAP[key] || null
}

export function getPlantsByCategory() {
  const grouped = {}
  CAT_ORDER.forEach(cat => { grouped[cat] = [] })
  PLANT_DB.forEach(p => {
    if (grouped[p.cat]) grouped[p.cat].push(p)
  })
  return grouped
}

export function getMonthlyTasks(plantKeys, month) {
  const tasks = []
  plantKeys.forEach(key => {
    const plant = PLANT_MAP[key]
    if (!plant) return
    const monthTasks = plant.seasonal[month] || []
    monthTasks.forEach((task, idx) => {
      tasks.push({ task, plant: plant.name, emoji: plant.emoji, plantKey: key, idx })
    })
  })
  return tasks
}

export const MONTH_NAMES = [
  'Januar','Februar','Mars','April','Mai','Juni',
  'Juli','August','September','Oktober','November','Desember'
]

export const CITIES = [
  { name:'Oslo',         info:'Sone 5 · Sørøst-Norge' },
  { name:'Bergen',       info:'Sone 8 · Vestlandet' },
  { name:'Trondheim',    info:'Sone 6 · Midt-Norge' },
  { name:'Stavanger',    info:'Sone 8 · Rogaland' },
  { name:'Tromsø',       info:'Sone 3 · Nord-Norge' },
  { name:'Kristiansand', info:'Sone 8 · Sørlandet' },
  { name:'Drammen',      info:'Sone 5 · Sørøst-Norge' },
  { name:'Fredrikstad',  info:'Sone 5 · Østfold' },
  { name:'Bodø',         info:'Sone 4 · Nord-Norge' },
  { name:'Ålesund',      info:'Sone 7 · Vestlandet' },
  { name:'Hamar',        info:'Sone 5 · Innlandet' },
  { name:'Lillehammer',  info:'Sone 4 · Innlandet' },
]

export const DIR_HINTS = {
  N:  'Nordvendt — fokuser på skyggetolerante vekster som rips og syriner',
  NE: 'Nordøstvendt — morgen-sol, passer mange hardføre vekster',
  E:  'Østvendt — god morgensol, passer for de fleste urter',
  SE: 'Sørøstvendt — mye sol, ideelt for de fleste grønnsaker',
  S:  'Sørvendt — ideelt for sol- og varmekjære vekster som tomat og agurk',
  SW: 'Sørvestvendt — ettermiddagssol, flott for roser og bærbusker',
  W:  'Vestvendt — ettermiddagssol, passer for mange blomster og bær',
  NW: 'Nordvestvendt — begrenset sol, velg hardføre vekster',
}

export const LOG_ACTIVITIES = [
  { type:'vanning',      label:'Vanning',       emoji:'💧' },
  { type:'gjødsling',    label:'Gjødsling',      emoji:'🌱' },
  { type:'plantenæring', label:'Plantenæring',   emoji:'🧪' },
  { type:'beskjæring',   label:'Beskjæring',     emoji:'✂️' },
  { type:'sprøyting',    label:'Sprøyting',      emoji:'🚿' },
  { type:'repotting',    label:'Repotting',      emoji:'🪴' },
  { type:'høsting',      label:'Høsting',        emoji:'🧺' },
  { type:'luking',       label:'Luking/ugras',   emoji:'🌾' },
  { type:'stell',        label:'Generelt stell', emoji:'🌿' },
]

// Bakoverkompatibilitet
export const PLANTS = PLANT_MAP
export const CATEGORIES = {
  grønnsak:   { label:'Grønnsaker',                emoji:'🥦' },
  bær:        { label:'Bær',                       emoji:'🍓' },
  frukt:      { label:'Frukt',                     emoji:'🍎' },
  urt:        { label:'Urter',                     emoji:'🌿' },
  rose:       { label:'Roser',                     emoji:'🌹' },
  staude:     { label:'Stauder (flerårige)',        emoji:'🌸' },
  busk:       { label:'Busker og klatreplanter',   emoji:'🌿' },
  tre:        { label:'Trær',                      emoji:'🌳' },
  prydplante: { label:'Prydplanter og løkblomster',emoji:'🌷' },
}
